//@ui5-bundle ui5/con/myDashboard/Component-preload.js
sap.ui.require.preload({
	"ui5/con/myDashboard/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","ui5/con/myDashboard/model/models"],function(e,i,t){"use strict";return e.extend("ui5.con.myDashboard.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(t.createDeviceModel(),"device")}})});
},
	"ui5/con/myDashboard/controller/App.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(n){"use strict";return n.extend("ui5.con.myDashboard.controller.controller.App",{onInit(){}})});
},
	"ui5/con/myDashboard/controller/BaseController.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/core/routing/History","sap/ui/core/UIComponent","ui5/con/myDashboard/model/formatter"],function(e,t,o,n){"use strict";return e.extend("ui5.con.myDashboard.controller.BaseController",{formatter:n,getModel:function(e){return this.getView().getModel(e)},setModel:function(e,t){return this.getView().setModel(e,t)},getResourceBundle:function(){return this.getOwnerComponent().getModel("i18n").getResourceBundle()},navTo:function(e,t,o){this.getRouter().navTo(e,t,o)},getRouter:function(){return o.getRouterFor(this)},onNavBack:function(){const e=t.getInstance().getPreviousHash();if(e!==undefined){window.history.back()}else{this.getRouter().navTo("appHome",{},true)}}})});
},
	"ui5/con/myDashboard/controller/MainView.controller.js":function(){sap.ui.define(["./BaseController","ui5/con/myDashboard/controllerExtension/DashboardFactory"],function(e,t){"use strict";return e.extend("ui5.con.myDashboard.controller.MainView",{onInit:function(){},dashboardFactory:function(e,F){return t(e,F)},editDashboard:function(e){e.getSource().getParent().getParent().setEditable(!e.getSource().getParent().getParent().getEditable())},randomizeColor:function(){var e=["#FF6633","#FFB399","#FF33FF","#FFFF99","#00B3E6","#E6B333","#3366E6","#999966","#99FF99","#B34D4D","#80B300","#809900","#E6B3B3","#6680B3","#66991A","#FF99E6","#CCFF1A","#FF1A66","#E6331A","#33FFCC","#66994D","#B366CC","#4D8000","#B33300","#CC80CC","#66664D","#991AFF","#E666FF","#4DB3FF","#1AB399","#E666B3","#33991A","#CC9999","#B3B31A","#00E680","#4D8066","#809980","#E6FF80","#1AFF33","#999933","#FF3380","#CCCC00","#66E64D","#4D80CC","#9900B3","#E64D66","#4DB380","#FF4D4D","#99E6E6","#6666FF"];const t=e.sort(()=>.5-Math.random());let F=t.slice(0,5);this.getView().getModel().oData.tiles.forEach(e=>{e.measureColour=F});this.getView().getModel().updateBindings()}})});
},
	"ui5/con/myDashboard/controllerExtension/DashboardFactory.js":function(){sap.ui.define(["ui5-cc-dndashboard/DashboardTile","ui5-cc-dndashboard/DashboardChart","ui5-cc-dndashboard/FunnelChart"],function(e,t,a){"use strict";function s(e,t){return Math.floor(Math.random()*(t-e+1)+e)}var i=function(e){var t=e.getSource().getModel().getProperty("/tiles");t.forEach(e=>{if(e.cardType!=="dndChart"){return}e.data.forEach(e=>{Object.keys(e).forEach(t=>{if(typeof e[t]=="number"){e[t]=e[t]*s(90,110)/100}})})});sap.ui.getCore().byId("__dashboard0").rerender()};return function(s,r){if(r.getProperty("cardType")==="dndChart"){return new e({posx:"{posx}",posy:"{posy}",width:"{width}",height:"{height}",content:new t({title:"{title}",chartType:"{chartType}",darkMode:sap.ui.getCore().getConfiguration().getTheme().indexOf("dark")>0?true:false,measure:"{measure}",dimension:"{dimension}",data:"{data}",measureColour:"{measureColour}",xGrid:"{xGrid}",yGrid:"{yGrid}",xAxisLabel:"{xAxisLabel}",yAxisLabel:"{yAxisLabel}",showLegend:"{showLegend}",legendPosition:"{legendPosition}",enableFilledLine:"{enableFilledLine}",enableAxisLabels:"{enableAxisLabels}",label:"{label}",scatterLabel:"{scatterLabel}",smartNumberFormat:"{smartNumberFormat}",xAxisUOM:"{xAxisUOM}",yAxisUOM:"{yAxisUOM}",showDataPoints:"{showDataPoints}",dataPointColor:"{dataPointColor}",y2AxisUOM:"{y2AxisUOM}",y2AxisLabel:"{y2AxisLabel}",stacked:"{stacked}"})})}else if(r.getProperty("cardType")==="image"){return new e({posx:"{posx}",posy:"{posy}",width:"{width}",height:"{height}",content:new sap.m.Image({height:"3rem",src:"{url}"})})}else if(r.getProperty("cardType")==="select"){return new e({posx:"{posx}",posy:"{posy}",width:"{width}",height:"{height}",content:new sap.m.VBox({items:[new sap.m.Label({text:"{text}"}),new sap.m.ComboBox({width:"100%",change:function(e){i(e)},items:{path:"items",template:new sap.ui.core.Item({text:"{name}"})}})]})})}else if(r.getProperty("cardType")==="list"){return new e({posx:"{posx}",posy:"{posy}",width:"{width}",height:"{height}",content:new sap.m.VBox({items:[new sap.m.Label({text:"{text}"}),new sap.m.List({selectionChange:function(e){i(e)},mode:"MultiSelect",items:{path:"items",template:new sap.m.StandardListItem({title:"{name}",selected:"{selected}"})}})]})})}else if(r.getProperty("cardType")==="funnel"){return new e({posx:"{posx}",posy:"{posy}",width:"{width}",height:"{height}",content:new a({measure:"{measure}",dimension:"{dimension}",data:"{data}",measureColour:"{measureColour}"})})}}});
},
	"ui5/con/myDashboard/i18n/i18n.properties":'# This is the resource bundle for ui5.con.myDashboard\n\n#Texts for manifest.json\n\n#XTIT: Application name\nappTitle=Title of ui5.con.myDashboard\n\n#YDES: Application description\nappDescription=Description of ui5.con.myDashboard\r\n#XTIT: Main view title\ntitle=Title of ui5.con.myDashboard',
	"ui5/con/myDashboard/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"ui5.con.myDashboard","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","sourceTemplate":{"id":"@sap-ux/fiori-freestyle-writer:basic","version":"0.11.15"},"dataSources":{"localData":{"uri":"utils/Data.json","type":"JSON"}}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":true,"dependencies":{"minUI5Version":"1.60.0","libs":{"sap.m":{},"sap.ui.core":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"ui5.con.myDashboard.i18n.i18n"}},"":{"type":"sap.ui.model.json.JSONModel","dataSource":"localData"}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"ui5.con.myDashboard.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteMainView","pattern":":?query:","target":["TargetMainView"]}],"targets":{"TargetMainView":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"MainView","viewName":"MainView"}}},"rootView":{"viewName":"ui5.con.myDashboard.view.App","type":"XML","async":true,"id":"App"}}}',
	"ui5/con/myDashboard/model/formatter.js":function(){sap.ui.define([],function(){"use strict";return{}});
},
	"ui5/con/myDashboard/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){const i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"ui5/con/myDashboard/view/App.view.xml":'<mvc:View controllerName="ui5.con.myDashboard.controller.App" xmlns:html="http://www.w3.org/1999/xhtml" xmlns:mvc="sap.ui.core.mvc" displayBlock="true" xmlns="sap.m"><App id="app"></App></mvc:View>\n',
	"ui5/con/myDashboard/view/MainView.view.xml":'<mvc:View controllerName="ui5.con.myDashboard.controller.MainView" xmlns:mvc="sap.ui.core.mvc" displayBlock="true" xmlns="sap.m" xmlns:dnd="ui5-cc-dndashboard"><Page id="page" title="{i18n>title}"><dnd:Dashboard class="sapUiSmallMargin" height="80vh"\r\n            tiles="{\r\n                path:\'/tiles\',\r\n                factory: \'.dashboardFactory\'\r\n            }"\r\n        ><dnd:header><Toolbar><Title text="My Dashboard"/><ToolbarSpacer/><Button icon="sap-icon://edit" text="Edit Dashboard" press="editDashboard"/><Button icon="sap-icon://refresh" text="Randomize Color" press="randomizeColor"/></Toolbar></dnd:header></dnd:Dashboard></Page></mvc:View>\r\n'
});
